@startuml
'https://plantuml.com/class-diagram

class Customer
class Event
class Booking
class Location

Customer "1" *-- "many" Booking
Booking "many" *-- "1" Event
Event "many" *-- "1" Location

@enduml